define(function(require) {
  var
    t0 = require('text!/templates/answers-list-entry.html'),
    t1 = require('text!/templates/books-card-edit.html'),
    t2 = require('text!/templates/books-card.html'),
    t3 = require('text!/templates/books-card-o.html'),
    t4 = require('text!/templates/books-list-entry.html'),
    t5 = require('text!/templates/books-list-entry-loading.html'),
    t6 = require('text!/templates/books-list-entry-no-image.html'),
    t7 = require('text!/templates/comments-list-entry.html'),
    t8 = require('text!/templates/list-loading.html'),
    t9 = require('text!/templates/lst'),
    t10 = require('text!/templates/post-book-edit.html'),
    t11 = require('text!/templates/post-form.html'),
    t12 = require('text!/templates/questions-card.html'),
    t13 = require('text!/templates/questions-entry-loading.html'),
    t14 = require('text!/templates/questions-list-entry.html'),
    t15 = require('text!/templates/ret'),
    t16 = require('text!/templates/reviews-list-entry.html'),
    t17 = require('text!/templates/script'),
    t18 = require('text!/templates/signin.html'),
    t19 = require('text!/templates/signup.html'),
    t20 = require('text!/templates/static-test.html');

  return {
    'answers-list-entry': t0,
    'books-card-edit': t1,
    'books-card': t2,
    'books-card-o': t3,
    'books-list-entry': t4,
    'books-list-entry-loading': t5,
    'books-list-entry-no-image': t6,
    'comments-list-entry': t7,
    'list-loading': t8,
    'lst': t9,
    'post-book-edit': t10,
    'post-form': t11,
    'questions-card': t12,
    'questions-entry-loading': t13,
    'questions-list-entry': t14,
    'ret': t15,
    'reviews-list-entry': t16,
    'script': t17,
    'signin': t18,
    'signup': t19,
    'static-test': t20,
  }
})